require:
  - standard/cop/semantic_blocks
  - rubocop-md

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'lib/generators/**/templates/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Standard/SemanticBlocks:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Layout/AlignParameters:
  EnforcedStyle: with_first_parameter

Lint/Void:
  Exclude:
    - '**/*.md'

# See https://github.com/rubocop-hq/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
    - '**/*.md'

Lint/DuplicateMethods:
  Exclude:
    - '**/*.md'

Naming/FileName:
  Exclude:
   - '**/*.md'

Layout/InitialIndentation:
  Exclude:
    - 'CHANGELOG.md'
