require:
  - standard/cop/block_single_line_braces
  - ruby-next/rubocop

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'lib/generators/**/templates/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: next

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/FileName:
  Exclude:
   - '**/*.md'
