require:
  - rubocop-md

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'test/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'gemfiles/**/*'
    - 'test/dummy/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/Void:
  Exclude:
    - '**/*.md'

Lint/DuplicateMethods:
  Exclude:
    - '**/*.md'

Naming/FileName:
  Exclude:
   - 'Rakefile'
   - 'Gemfile'
   - '**/*.md'

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'test/**/*.rb'
    - '**/*.md'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
