source "https://rubygems.org"

gem "wasmify-rails", "~> 0.4.0"

gem "rails", "~> 8.0.0"

gem "action_policy", path: "../.."

# rails new gems
gem "propshaft"

# other rails deps
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data"
