name: JRuby Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ hashFiles('**/gemfiles/jruby.gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - name: Bundle install
      run: |
        bundle config --global gemfile gemfiles/jruby.gemfile
        bundle config path /home/runner/bundle
        bundle install
        bundle update
    - name: Run tests
      run: |
        bundle exec rake test:ci
