name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7"]
        gemfile: [
          "gemfiles/railsmaster.gemfile",
          "gemfiles/rails6.gemfile"
        ]
        exclude:
        - ruby: "2.5"
          gemfile: "gemfiles/railsmaster.gemfile"
        - ruby: "2.5"
          gemfile: gemfiles/railsmaster.gemfile"
        include:
        - ruby: "2.4"
          gemfile: "gemfiles/rails42.gemfile"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles(matrix.gemfile) }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run tests
      run: |
        bundle exec rake test:ci
