name: Deploy Tutorial
on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: tutorial
  cancel-in-progress: false

jobs:
  transpile:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
    - name: Run Ruby Next
      run: bundle exec rake nextify
    - name: Upload .rbnext
      uses: actions/upload-artifact@v4
      with:
        name: rbnext
        path: './lib/.rbnext'
        include-hidden-files: true

  build:
    runs-on: ubuntu-latest
    needs: transpile
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          name: rbnext
          path: './lib/.rbnext'
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.74.0
      - name: Install wasi-vfs
        env:
          WASI_VFS_VERSION: 0.5.4
        run: |
          curl -LO "https://github.com/kateinoigakukun/wasi-vfs/releases/download/v${WASI_VFS_VERSION}/wasi-vfs-cli-x86_64-unknown-linux-gnu.zip"
          unzip wasi-vfs-cli-x86_64-unknown-linux-gnu.zip
          mv wasi-vfs /usr/local/bin/wasi-vfs
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: tutorial/ruby-wasm/Gemfile
          BUNDLE_PATH: tutorial/ruby-wasm/vendor
        with:
          ruby-version: 3.3
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 'tutorial/package-lock.json'
      - name: Cache ruby.wasm artefacts
        id: cache-ruby-wasm
        uses: actions/cache@v4
        with:
          path: |
            tutorial/ruby-wasm/build
            tutorial/ruby-wasm/rubies
          key: ${{ runner.os }}-v1-ruby-wasm
      - name: Build ruby.wasm
        working-directory: ./tutorial
        run: |
          npm run build:wasm
      - name: Build tutorial
        working-directory: ./tutorial
        run: |
          npm install
          npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: tutorial-dist
          path: './tutorial/dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          name: tutorial-dist
          path: tutorial/dist
      - uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: './tutorial/dist'
          netlify-config-path: './tutorial/netlify.toml'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
